### PR TITLE
feat: storage proof blog post

### PR DESCRIPTION
**Pull request by 0xParticle**
added a new blog post.
we should hide the "liveness" post from the Insights section, but keep it alive on the web.

### CODE REVIEW

**Comment by turtlemoji** [comment]
image
 @0xArdy

**Review by 0xArdy — DISMISSED** [review]
lgtm!

**Comment by 0xArdy** [comment]
> image @0xArdy

solved here https://github.com/defi-wonderland/web/pull/73/commits/99f724c01edf0cdbcb105f0121fdace463825bac

**Review by 0xArdy — APPROVED** [review]

**Comment by 0xArdy** [comment]
Closed because the Vercel preview is bugged

**Pull request closed without merging**
